apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
spec:
  destination:
    namespace: pihole
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://mojo2600.github.io/pihole-kubernetes/
      targetRevision: "2.14.0"
      chart: pihole
      helm:
        releaseName: pihole
        valueFiles: 
          - $values/k8s-apps/pihole/values.yaml
    - repoURL: https://github.com/KGB33/homelab.git
      ref: values
      targetRevision: HEAD
      path: k8s-apps/pihole/
  syncPolicy:
    syncOptions:
      - CreateNamespace=true