---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-app # Name of the deployment
  namespace: argocd # Name of the namespace
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      app: pihole-app # Name of your application
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pihole-app # Name of your application
    spec:
      containers:
        # Containers are the individual pieces of your application that you want
        # to run.
        - name: pihole # Name of the container
          image: pihole/pihole:latest # The image you want to run
          env:
            - name: TZ
              value: 'America/NewYork'
            - name: WEBPASSWORD
              value: 'changeme'
            - name: PIHOLE_DNS_
              value: '1.1.1.1;8.8.8.8;8.8.4.4'
            - name: QUERY_LOGGING
              value: 'false'
          ports:
            # Ports are the ports that your application uses.
            - containerPort: 80 # The port that your application uses
            - containerPort: 53
            - containerPort: 67
          livenessProbe:
            httpGet:
              path: /admin
              port: 80
            periodSeconds: 3600
          startupProbe:
            httpGet:
              path: /admin
              port: 80
            failureThreshold: 6
            periodSeconds: 10
          volumeMounts:
            - mountPath: /etc/pihole
              subPath: custom.list
              name: lv-storage
      volumes:
        # Volumes are the persistent storage that your application uses.
        - name: lv-storage # Name of the volume
          persistentVolumeClaim:
            claimName: pihole-pvc # Name of the persistent volume claim
        # Volumes are the persistent storage that your application uses.
---
apiVersion: v1
kind: Service
metadata:
  name:  pihole-dns
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    app: pihole-app
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-app
  namespace: argocd
spec:
  selector:
    app: pihole-app
  type: LoadBalancer
  ports:
    - name: pihole
      protocol: TCP
      port: 80
      targetPort: 80
  loadBalancerIP: 192.168.253.210