apiVersion: v1
kind: Service
metadata:
  name: pihole
spec:
  selector:
    app: pihole
  type: LoadBalancer
  ports:
    - name: pihole
      protocol: TCP
      port: 80
      targetPort: 80
  loadBalancerIP: 192.168.0.210