apiVersion: v1
kind: Service
metadata:
  name: pihole-app
  namespace: argocd
spec:
  selector:
    app: pihole-app
  type: LoadBalancer
  ports:
    - name: pi-hole.cluster.local
      protocol: TCP
      port: 80
      targetPort: 80
  loadBalancerIP: 192.168.253.210