apiVersion: v1
kind: Service
metadata:
  name: pihole-app
spec:
  selector:
    app: pihole-app
  type: LoadBalancer
  ports:
    - name: pi-hole
      protocol: TCP
      port: 80
      targetPort: 80
  loadBalancerIP: 192.168.0.210