apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-pvc
  namespace: argocd
  labels:
    app: homebridge-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi