---
apiVersion: v1
kind: Service
metadata:
  name: firefly-iii
  labels:
    app: firefly-iii
spec:
  ports:
    - name: firefly-iii
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: firefly-iii
    tier: frontend
  type: LoadBalancer
  loadBalancerIP: 192.168.253.212